### ISSUE TITLE
Feature thought

### ISSUE THREAD

**Issue by CWen001** [TyberiusPrime/dppd#1]
First, thank you very much for this wonderful library. I have noticed this library since December and used it for a while. It really helps me ease the data manipulation in pandas. May I have some feature thoughts from a python newbie perspective.

Maybe you have known some recent attempts that try to bring the best of dplyr to Python, like [`pyjanitor`](https://github.com/ericmjl/pyjanitor) built on [`pandas_flavor`](https://github.com/Zsailer/pandas_flavor). Pyjanitor in my mind has two main advantages (1) simple import and can always return pandas.DataFrame after chain methods directly. (2) pandas_flavor depends on pandas 0.23+ new added API for registering accessors with Pandas objects, and it is possible to be extended to geopandas and dask in future.

However, I found the API design of dppd is more familiar, concise, and elegant. For an R user, it is as intuitive as almost no learning cost. As a dppd user who wants to recommend it to my colleagues, I'm wondering If dppd have further development plan; and what are the advantages of dppd's object compared with pandas_flavor's approach?

**Comment by TyberiusPrime** [comment]
Hello @Cwen001, 
Thank you for your feedback, it is nice to hear that somebody out there has taken interest.

Compared to pandas_flavours, dppd is a bit cleaner since our monkey patched methods are only visible on the dp()ed object, not on all Dataframes. Flavors and pandas 0.23+ offers namespacing with accessors which is just as clean, though considering the number of characters a bit more tedious than the dp()...pd approach.

Dppd is more powerful in the sense that it can also patched other objects (check out https://pypi.org/project/dppd-plotnine/ ).

Extension to dask or geopandas should be straightforward - write tests and either enable the existing implementations for the new class (if API is compatible) or write the verb anew.

But the biggest difference I see in the proxy-X object which let's you use the latest created dataframe inline. 

This is also what separates dppd from the other dplyr adaptations, which all try to (and fail to) introduce R's non standard evaluation for the same purpose.

Honestly there are only to regions where any of this is better than plain pandas, the magic X and the column selection mini language. Otherwise the pandas methods nowadays mostly allow.method chaining (=pipe operator in R).

As for the future, I have no immediate plans. There will be some more convenience verbs when I run across them, but breaking changes to existing ones are fairly unlikely.

I'm also not planning on doing any extension to other DataFrames, just because I personally don't have a need right now. But I would not mind a PR in that direction.

Lately, I've had a lot of joy with the very complete toolset Rust offers on iterators - it's based on method chaining and reads like "something.iter().filter().map().skip()...." And I might implement a dppd_iterators.

So long,
Florian

**Comment by CWen001** [comment]
Thank you very much for the prompt and detailed response. Now I have a better understanding of proxy-X object, as it is well-documented. It also reminds me of the imported `f` object in`pydatable`(https://github.com/h2oai/datatable) although the mechanisms may be different. Personally, when I import dppd at the beginning, I would like to import X as f. Because the capital X sometimes has to be indicating a design matrix, for instance, in accordance with the convention of data analysis like in scikit-learn.

Thanks again for your thoughts and for this library. I will take a closer look at other dppd related libraries. Now I close the issue as questions are answered.

Greetings from Hannover.
Chen

**Comment by TyberiusPrime** [comment]
I had a look at pydatatable's f object - it's another 'expression builder' object, not a proxy for the latest created object.
